//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDB
{
       
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;  
    using CMDB;
         
    /// <summary> 
    /// 系统用户
    /// </summary>
    [Serializable]
    public partial class SY_User     
    {
         /// <summary>
         /// 主键
         /// </summary>
       [Col_(IsPrimaryKey = true, IsIdentity = true)]
         public int Id { get; set; }
         /// <summary>
         /// 认证方式userlogintype。0用户+口令(传统)，1二维码等
         /// </summary>
         public int LoginType { get; set; }
         /// <summary>
         /// 用户类型usertype。0普通用户、1管理员用户，2超级管理员root
         /// </summary>
         public int UserType { get; set; }
         /// <summary>
         /// 是否删除。false|true
         /// </summary>
         public bool IsDelete { get; set; }
         /// <summary>
         /// 序号
         /// </summary>
         public Nullable<int> AriSeq { get; set; }
         /// <summary>
         /// 用户名
         /// </summary>
         public string UserCode { get; set; }
         /// <summary>
         /// 用户姓名
         /// </summary>
         public string RealName { get; set; }
         /// <summary>
         /// 账号状态datastate。0正常，1停用
         /// </summary>
         public int State { get; set; }
         /// <summary>
         /// 用户密码
         /// </summary>
         public string Pwd { get; set; }
         /// <summary>
         /// 创建时间
         /// </summary>
         public Nullable<System.DateTime> CreateTime { get; set; }
         /// <summary>
         /// 是否有外网访问权限。false|true
         /// </summary>
         public bool InternetAccess { get; set; }
         /// <summary>
         /// 备注
         /// </summary>
         public string AriDesc { get; set; }
         /// <summary>
         /// 邮箱
         /// </summary>
         public string Email { get; set; }
         /// <summary>
         /// 手机号
         /// </summary>
         public string Phone { get; set; }
         /// <summary>
         /// 上次登录时间
         /// </summary>
         public Nullable<System.DateTime> LastLogin { get; set; }
         /// <summary>
         /// 员工档案名称
         /// </summary>
         public Nullable<int> EmployeeID { get; set; }
         /// <summary>
         /// 安全认证模式userveirify。0未认证，1邮箱，2手机，3全部
         /// </summary>
         public Nullable<int> Verify { get; set; }
         /// <summary>
         /// 接收通知类型usernotice。0无，1邮箱，2手机短信，3全部
         /// </summary>
         public Nullable<int> GetNotice { get; set; }
         /// <summary>
         /// 部门名称(同步自ba_employee表)
         /// </summary>
         public Nullable<int> DeptID { get; set; }
         /// <summary>
         /// 岗位名称(同步自ba_employee表)
         /// </summary>
         public Nullable<int> PostID { get; set; }
         /// <summary>
         /// 考勤所属部门（暂时不需要）
         /// </summary>
         public int AttDeptID { get; set; }
    }
}
